In [ ]:
import numpy as np

scores = np.array([
    [0.9, 0.8, 1.0],
    [0.4, 0.7, 0.9]
])

# 숫자 하나인 0.1을 배열의 모든 값에 더함
print(scores + 0.1)

[[1.  0.9 1.1]
 [0.5 0.8 1. ]]


In [2]:
#연습문제 1
import numpy as np

scores = np.array([
    [0.9, 0.8, 1.0],
    [0.4, 0.7, 0.9]
])

adjusted_scores = scores + np.array([0.1, 0.0, -0.2])

print(adjusted_scores)

[[1.  0.8 0.8]
 [0.5 0.7 0.7]]
