In [ ]:
# shape의 이해
import numpy as np

# scores는 몇 행, 몇 열인가.
scores = np.array([
#     1열   2열   3열 
# 1행[0.9, 0.8, 1.0],
# 2행[0.4, 0.7, 0.9],
# 3행[0.8, 0.9, 0.8]
])

#3행 3열

# 이 모양을 코드로 확인하는 것이 shape
print(scores.shape)

(0,)


In [ ]:
# reshape의 사용
import numpy as np

# reshape는 값의 순서를 유지하면서 배열의 모양을 바꿔줘
numbers = np.array([1, 2, 3 ,4, 5, 6])
# 지금은 일렬배열

reshaped = numbers.reshape(2, 3)
# reshape를 통해 2행 3열로 모양 변환

# [[1 2 3]
#  [4 5 6]]
print(reshaped)

# 모양을 바꾸어도 전체 원소 개수는 같아야함.

In [ ]:
# reshape의 응용
import numpy as np

numbers = np.array([1, 2, 3 ,4, 5, 6])

reshaped = numbers.reshape(2, -1)
# 전체 원소가 같아야 reshape이 된다, 편리한 기능 -1을 넣으면 그 자리의 크기를 자동으로 계산

print(reshaped)

rereshaped = numbers.reshape(-1, 2)

print(rereshaped)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
# -1을 사용해서 1차원 배열 만들기
import numpy as np

scores = np.arrayscores = np.array([
    [0.9, 0.8, 1.0],
    [0.4, 0.7, 0.9]
])

flat_scores = scores.reshape(-1)

# 이 때 flatschores에는 어떤 순서로 값이 들어가나
print(flat_scores)

#기존 값의 순서를 유지하며 모양만 바꿈

# scores = np.array([
#    [0.9, 0.8, 1.0],
#    [0.4, 0.7, 0.9]
#])

# [0.9, 0.8, 1. , 0.4, 0.7, 0.9]


[0.9 0.8 1.  0.4 0.7 0.9]
